Implemented storing meta data.

diff --git a/tests/lib b/tests/lib
--- a/tests/lib
+++ b/tests/lib
@@ -3,7 +3,7 @@ zero_or_die()
 {
   "$@"
   if [ $? != 0 ]; then
-    echo "Failed: $@"
+    echo "Failed: $@" >&2
     exit 1
   fi
 }
